# Generated by Django 4.0.5 on 2022-06-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='created_date',
            name='name',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='published_date',
            name='name',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='text',
            name='name',
            field=models.TextField(),
        ),
    ]
